import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { loadConfig } from "./config.js";
import { discoverCodexPluginSkills } from "./codex-plugin-skills.js";
import { resolveProjectInstructions } from "./project-instructions.js";
import { loadWorkspaceSkills } from "./skills.js";
import { WorkspaceRegistry } from "./workspaces.js";

const root = await mkdtemp(join(tmpdir(), "devspace-codex-context-"));
try {
  const project = join(root, "project"), home = join(root, "codex"), configDir = join(root, "config");
  await mkdir(join(project, "nested"), { recursive: true });
  await mkdir(home); await mkdir(configDir);
  const env = { DEVSPACE_CONFIG_DIR: configDir, DEVSPACE_ALLOWED_ROOTS: project,
    CODEX_HOME: home, DEVSPACE_OAUTH_OWNER_TOKEN: "test-owner-token-that-is-long-enough" };
  assert.equal(loadConfig(env).agentDir, home);
  assert.equal(loadConfig({ ...env, DEVSPACE_AGENT_DIR: root }).agentDir, root);
  await writeFile(join(configDir, "config.json"), JSON.stringify({ agentDir: project }));
  assert.equal(loadConfig(env).agentDir, project);
  await rm(join(configDir, "config.json"));
  const config = loadConfig(env);
  await writeFile(join(home, "AGENTS.md"), "Global guidance\n");
  await writeFile(join(project, "AGENTS.md"), "Project guidance\n");
  await writeFile(join(project, "nested", "AGENTS.override.md"), "Nested guidance\n");
  const registry = new WorkspaceRegistry(config);
  const opened = await registry.openWorkspace(project);
  assert.deepEqual(opened.instructionChain.sources.map((source) => source.content), ["Global guidance\n", "Project guidance\n"]);
  const chain = await registry.getInstructionChain(opened.workspace, join(project, "nested"));
  assert.match(chain.instructions, /Global guidance[\s\S]*Project guidance[\s\S]*Nested guidance/);
  await writeFile(join(home, "AGENTS.override.md"), "Global override\n");
  const changed = await registry.preflightInstructions(opened.workspace);
  assert.match(changed!.instructions, /Global override/);
  assert.doesNotMatch(changed!.instructions, /Global guidance/);
  assert.equal(await registry.preflightInstructions(opened.workspace), undefined);
  await writeFile(join(home, "AGENTS.override.md"), "  \n");
  assert.match((await registry.getInstructionChain(opened.workspace)).instructions, /Global guidance/);
  const limited = await resolveProjectInstructions(project, project, { fallbackFileNames: [], maxBytes: 7 }, home);
  assert.equal(limited.instructions, "Global "); assert.equal(limited.truncated, true);
  const absent = await resolveProjectInstructions(project, project, config.projectInstructions, join(root, "absent"));
  assert.equal(absent.sources.length, 1);

  const installed = join(home, "plugins", "cache", "personal", "video", "1.0.0");
  const skills = join(installed, "skills"), skill = join(skills, "video");
  await mkdir(join(installed, ".codex-plugin"), { recursive: true });
  await mkdir(skill, { recursive: true });
  const manifest = join(installed, ".codex-plugin", "plugin.json");
  await writeFile(manifest, JSON.stringify({ name: "video", skills: "./skills/" }));
  await writeFile(join(skill, "SKILL.md"), "---\nname: video\ndescription: Analyze a video.\n---\nUse the script.\n");
  assert.deepEqual(discoverCodexPluginSkills(home), { paths: [], diagnostics: [] });
  const configPath = join(home, "config.toml");
  await writeFile(configPath, '[plugins."video@personal"]\nenabled = false\n');
  assert.deepEqual(discoverCodexPluginSkills(home).paths, []);
  await writeFile(configPath, '[plugins."video@personal"]\nenabled = true\n');
  assert.deepEqual(discoverCodexPluginSkills(home).paths, [skills]);
  assert.equal(loadWorkspaceSkills(config, project).skills.some((item) => item.name === "video"), true);
  assert.deepEqual(loadWorkspaceSkills({ ...config, skillsEnabled: false }, project).skills, []);
  await mkdir(join(installed, "..", "2.0.0"));
  assert.deepEqual(discoverCodexPluginSkills(home).paths, []);
  assert.match(discoverCodexPluginSkills(home).diagnostics[0].message, /2 cached versions/);
  await rm(join(installed, "..", "2.0.0"), { recursive: true });
  await writeFile(manifest, JSON.stringify({ name: "video", skills: "../../../../../" }));
  assert.deepEqual(discoverCodexPluginSkills(home).paths, []);
  assert.equal(discoverCodexPluginSkills(home).diagnostics.length, 1);
  await writeFile(manifest, JSON.stringify({ name: "wrong", skills: "./skills" }));
  assert.deepEqual(discoverCodexPluginSkills(home).paths, []);
  await writeFile(manifest, JSON.stringify({ name: "video", skills: ["./skills"] }));
  assert.deepEqual(discoverCodexPluginSkills(home).paths, [skills]);
  await writeFile(configPath, '[plugins."../video@personal"]\nenabled = true\n');
  assert.deepEqual(discoverCodexPluginSkills(home).paths, []);
  await writeFile(configPath, 'secret = "DO_NOT_ECHO_THIS"\n[broken');
  assert.deepEqual(discoverCodexPluginSkills(home).paths, []);
  assert.doesNotMatch(JSON.stringify(discoverCodexPluginSkills(home).diagnostics), /DO_NOT_ECHO_THIS/);
  if (process.platform !== "win32") {
    await writeFile(configPath, '[plugins."video@personal"]\nenabled = true\n');
    await symlink(join(root, "outside.md"), join(skill, "escape.md"));
    assert.deepEqual(discoverCodexPluginSkills(home).paths, []);
    await rm(join(skill, "escape.md"));
    await rm(join(home, "AGENTS.override.md")); await rm(join(home, "AGENTS.md"));
    await writeFile(join(root, "outside.md"), "Outside guidance\n");
    await symlink(join(root, "outside.md"), join(home, "AGENTS.md"));
    assert.equal((await registry.getInstructionChain(opened.workspace)).sources.length, 1);
    await rm(join(home, "AGENTS.md"));
    await writeFile(join(home, "inside.md"), "Inside linked guidance\n");
    await symlink("inside.md", join(home, "AGENTS.md"));
    assert.match((await registry.getInstructionChain(opened.workspace)).instructions, /Inside linked guidance/);
  }
} finally { await rm(root, { recursive: true, force: true }); }
console.log("Codex context tests passed.");
